# Generated by Django 4.2.9 on 2024-01-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_active_courseinstance_active_quiz_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='courseinstance',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='active',
            new_name='is_active',
        ),
    ]
