# Generated by Django 4.2.9 on 2024-01-15 02:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_questionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTextTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_tasks', to='school.topic')),
            ],
        ),
    ]
